name: 'Terraform CI'

on:
  push:
    branches:
    - 'feature/**'
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set Google Cloud credentials
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'jit-access@tasleem-project-trial-project.iam.gserviceaccount.com' # my-service-account@my-project.iam.gserviceaccount.com
        workload_identity_provider: 'projects/1090346272794/locations/global/workloadIdentityPools/66deg-jit-github/providers/jit-access' # "projects/123456789/locations/global/workloadIdentityPools/WIF_POOL/providers/WIF_PROVIDER"
     

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve